name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: "41 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compile C Program
      run: gcc -o my_program test.c

    - name: Run Executable
      run: ./my_program
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
        name: Build-Artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}
        # The desired behavior if no files are found using the provided path.
